### ISSUE TITLE
Invoke of 'gitlab:index/getGroup:getGroup' failed: rpc error: code = Canceled desc = context canceled ()

### ISSUE THREAD

**Issue by mklueh** [pulumi/pulumi-gitlab#31]
Hi there,

I´m trying to use this plugin, but it occasionally fails with the error below:

```
 Error: Invoke of 'gitlab:index/getGroup:getGroup' failed: rpc error: code = Canceled desc = context canceled ()
        at deserializeResponse (C:\Users\My-PC\IdeaProjects\MyProject\infrastructure\node_modules\@pulumi\gitlab\node_modules\@pulumi\pulumi\runtime\invoke.js:317:15)
        at invokeSyncWorker (C:\Users\My-PC\IdeaProjects\MyProject\infrastructure\node_modules\@pulumi\gitlab\node_modules\@pulumi\pulumi\runtime\invoke.js:208:25)
        at invokeSync (C:\Users\My-PC\IdeaProjects\MyProject\infrastructure\node_modules\@pulumi\gitlab\node_modules\@pulumi\pulumi\runtime\invoke.js:101:12)
        at Object.invoke (C:\Users\My-PC\IdeaProjects\MyProject\infrastructure\node_modules\@pulumi\gitlab\node_modules\@pulumi\pulumi\runtime\invoke.js:84:24)
        at Object.getGroup (C:\Users\My-PC\IdeaProjects\MyProject\infrastructure\node_modules\@pulumi\getGroup.ts:47:61)
        at GitlabProvider.deploy (C:\Users\My-PC\IdeaProjects\MyProject\infrastructure\gitlab\GitlabProvider.ts:19:30)
        at C:\Users\My-PC\IdeaProjects\MyProject\infrastructure\index.ts:54:24
        at C:\Users\My-PC\IdeaProjects\MyProject\infrastructure\node_modules\@pulumi\kubernetes\node_modules\@pulumi\pulumi\output.js:220:35
        at Generator.next (<anonymous>)
        at C:\Users\My-PC\IdeaProjects\MyProject\infrastructure\node_modules\@pulumi\kubernetes\node_modules\@pulumi\pulumi\output.js:21:71
```

Which seems to be related to https://github.com/terraform-providers/terraform-provider-github/issues/291

**Comment by mikhailshilkov** [comment]
The upstream link doesn't work anymore. Since the issue has no repro, and got no comments or upvotes in three years, I'll close it as non-actionable.
